### ISSUE TITLE
connectionLost回调后重连失败,建议startservice时考虑Android8以上的兼容问题

### ISSUE THREAD

**Issue by hello-earth** [fighter-lee/EasyMqtt#12]
Not allowed to start service Intent { cmp=com.dfd.ccccccc/top.fighter_lee.mqttlibs.mqtt_service.MqttService }: app is in background uid UidRecord{c865764 u0a245 SVC  bg:+1m6s737ms idle change:idle procs:2 proclist:28674,28718, seq(0,0,0)}

**Comment by hello-earth** [comment]
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1666)
at android.app.ContextImpl.startService(ContextImpl.java:1611)
at android.content.ContextWrapper.startService(ContextWrapper.java:677)
at top.fighter_lee.mqttlibs.mqtt_service.MqttAndroidClient.connect(MqttAndroidClient.java:413)
at top.fighter_lee.mqttlibs.connect.ConnectCommand.execute(ConnectCommand.java:244)
at top.fighter_lee.mqttlibs.connect.MqttManager.connect(MqttManager.java:58)
