### ISSUE TITLE
如何升级AndroidX

### ISSUE THREAD

**Issue by Wxianpeng** [fighter-lee/EasyMqtt#14]
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
        at top.fighter_lee.mqttlibs.mqtt_service.MqttService.callbackToActivity(MqttService.java:297)
        at top.fighter_lee.mqttlibs.mqtt_service.MqttConnection.publish(MqttConnection.java:541)
        at top.fighter_lee.mqttlibs.mqtt_service.MqttService.publish(MqttService.java:454)
        at top.fighter_lee.mqttlibs.mqtt_service.MqttAndroidClient.publish(MqttAndroidClient.java:719)
        at top.fighter_lee.mqttlibs.connect.PubCommand.execute(PubCommand.java:68)
        at top.fighter_lee.mqttlibs.connect.MqttManager.pub(MqttManager.java:82)

 Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.ubains.iflytekcontrol-2/base.apk"],nativeLibraryDirectories=[/data/app/com.ubains.iflytekcontrol-2/lib/arm64, /system/lib64, /vendor/lib64

**Comment by fighter-lee** [comment]
导入support V4包；
