### ISSUE TITLE
连接后订阅主题后，断开连接 解除订阅失败

### ISSUE THREAD

**Issue by LinYh08** [fighter-lee/EasyMqtt#9]
05-16 19:37:20.894 29858-29858/com.szyh.hangzhouvanke E/MqttEngine: onFailure
     (32102)
        at top.fighter_lee.mqttlibs.mqttv3.internal.ClientState.resolveOldTokens(ClientState.java:1104)
        at top.fighter_lee.mqttlibs.mqttv3.internal.ClientComms.handleOldTokens(ClientComms.java:441)
        at top.fighter_lee.mqttlibs.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:363)
        at top.fighter_lee.mqttlibs.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:734)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by fighter-lee** [comment]
你应该先unSub，然后再disconnect
